version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: libraryDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: libraryDB
    ports:
      - "5432:5432"
    volumes:

      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql