spring.application.name=LibraryApp

server.tomcat.threads.max=4000


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/libraryDB
#spring.datasource.username=postgres
#spring.datasource.password=2004
#spring.datasource.hikari.connection-timeout=300000
#spring.datasource.hikari.maximum-pool-size=4000

# Baza G?ówna (Zapis/Odczyt) - port 5432
app.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/libraryDB
app.datasource.primary.username=postgres
app.datasource.primary.password=2004

app.datasource.primary.maximum-pool-size=4000
app.datasource.primary.connection-timeout=300000

# Replika (Tylko Odczyt) - port 5433
app.datasource.replica.jdbc-url=jdbc:postgresql://localhost:5433/libraryDB
app.datasource.replica.username=postgres
app.datasource.replica.password=2004

app.datasource.replica.maximum-pool-size=4000
app.datasource.replica.connection-timeout=300000