spring.application.name=LibraryApp
spring.datasource.url=jdbc:postgresql://localhost:5432/libraryDB
spring.datasource.username=postgres
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver